# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"download_dataset": "00_image.ipynb",
         "ImageFeatureExtractor": "00_image.ipynb",
         "ImageFile.LOAD_TRUNCATED_IMAGES": "00_image.ipynb"}

modules = ["image.py"]

doc_url = "https://wittmannf.github.io/auto_feature_extraction/"

git_url = "https://github.com/wittmannf/auto_feature_extraction/tree/{branch}/"

def custom_doc_links(name): return None
