# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"download_dataset": "00_auto_feature_extraction.ipynb",
         "ImageFeatureExtractor": "00_auto_feature_extraction.ipynb",
         "ImageFile.LOAD_TRUNCATED_IMAGES": "00_auto_feature_extraction.ipynb",
         "PROJECT_FOLDER": "00_auto_feature_extraction.ipynb",
         "DATA_PATH": "00_auto_feature_extraction.ipynb",
         "DOGSCATS": "00_auto_feature_extraction.ipynb",
         "DOG_BREED_URL": "00_auto_feature_extraction.ipynb",
         "ZIP_FILENAME": "00_auto_feature_extraction.ipynb",
         "PETS": "00_auto_feature_extraction.ipynb",
         "TRAIN_PATH": "00_auto_feature_extraction.ipynb",
         "VALID_PATH": "00_auto_feature_extraction.ipynb"}

modules = ["auto_feature_extraction.py"]

doc_url = "https://wittmannf.github.io/auto_feature_extraction/"

git_url = "https://github.com/wittmannf/auto_feature_extraction/tree/{branch}/"

def custom_doc_links(name): return None
